spring:
  application:
    name: otp-service

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

otp:
  queue:
    name: otp.email.queue
    exchange: otp.exchange
    routing-key: otp.send
    dlq: otp.email.queue.dlq
    dlx: otp.exchange.dlx

hmac:
  secret-key: ${HMAC_SECRET_KEY}