spring:
  application:
    name: otp-service

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:guest}

  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}

otp:
  expiry-minutes: ${OTP_EXPIRY_MINUTES:5}
  resend-cooldown-seconds: ${OTP_RESEND_COOLDOWN_SECONDS:50}
  max-attempts: ${OTP_MAX_ATTEMPTS:3}
  queue:
    name: otp.email.queue
    exchange: otp.exchange
    routing-key: otp.send
    dlq: otp.email.queue.dlq
    dlx: otp.exchange.dlx

hmac:
  secret-key: ${HMAC_SECRET_KEY}

security:
  api-key: ${API_KEY}